/*
 Navicat Premium Data Transfer

 Source Server         : db_sahrudin
 Source Server Type    : MySQL
 Source Server Version : 100432 (10.4.32-MariaDB)
 Source Host           : localhost:3306
 Source Schema         : galenium_api_14122023

 Target Server Type    : MySQL
 Target Server Version : 100432 (10.4.32-MariaDB)
 File Encoding         : 65001

 Date: 15/12/2023 18:54:46
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for product_htu
-- ----------------------------
DROP TABLE IF EXISTS `product_htu`;
CREATE TABLE `product_htu`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_id` int NULL DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `status` enum('live','preview') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`, `status`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 440 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of product_htu
-- ----------------------------
INSERT INTO `product_htu` VALUES (1, 1, 'Busakan JF Anti Acne Cleanser Bar dengan air. ', 'Foam the JF Anti Acne Cleanser Bar with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (2, 1, 'Usapkan pada wajah yang telah dibilas dengan air.\n', 'Wash your face with the cleanser bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (3, 1, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (4, 1, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (5, 2, 'Busakan JF Anti Spot Care Cleanser Bar dengan air. ', 'Foam the JF Anti Acne Spot Cleanser Bar with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (6, 2, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (7, 2, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (8, 2, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (9, 3, 'Busakan JF Anti Protect Green Sensastion Cleanser Bar dengan air.', 'Foam the JF Anti Protect Green Sensastion Cleanser Bar with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (10, 3, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (11, 3, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (12, 3, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (13, 4, 'Busakan JF Anti Protect Blue Expression Cleanser Bar dengan air.', 'Foam the JF Anti Protect Blue Expression Cleanser Bar with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (14, 4, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (15, 4, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (16, 4, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (17, 5, 'Busakan dengan air dan usapkan pada wajah yang basah.', 'Foam JF Anti Acne Facial Foam with water and apply to damp face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (18, 5, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (19, 5, 'Bilas hingga bersih. \r\n', 'Wash face thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (20, 5, ' Untuk hasil optimal, lanjutkan dengan penggunaan JF Anti Acne Gel.', 'For best result, also apply JF Anti Acne Gel.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (21, 1, 'Busakan JF Anti Acne Cleanser Bar dengan air. ', 'Foam the JF Anti Acne Cleanser Bar with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (22, 1, 'Usapkan pada wajah yang telah dibilas dengan air.\n', 'Wash your face with the cleanser bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (23, 1, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (24, 1, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (25, 2, 'Busakan JF Anti Spot Care Cleanser Bar dengan air. ', 'Foam the JF Anti Acne Spot Cleanser Bar with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (26, 2, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (27, 2, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (28, 2, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (29, 3, 'Busakan JF Anti Protect Green Sensastion Cleanser Bar dengan air.', 'Foam the JF Anti Protect Green Sensastion Cleanser Bar with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (30, 3, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (31, 3, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (32, 3, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (33, 4, 'Busakan JF Anti Protect Blue Expression Cleanser Bar dengan air.', 'Foam the JF Anti Protect Blue Expression Cleanser Bar with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (34, 4, 'Usapkan pada wajah yang telah dibilas dengan air.', 'Wash your face with the cleanser bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (35, 4, 'Bilas wajah dengan air hingga bersih.', 'Rinse the face thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (36, 4, 'Gunakan secara teratur.', 'Use it regularly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (37, 5, 'Busakan dengan air dan usapkan pada wajah yang basah.', 'Foam JF Anti Acne Facial Foam with water and apply to damp face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (38, 5, 'Hindari bagian mata. ', 'Avoid Eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (39, 5, 'Bilas hingga bersih. \r\n', 'Wash face thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (40, 5, ' Untuk hasil optimal, lanjutkan dengan penggunaan JF Anti Acne Gel.', 'For best result, also apply JF Anti Acne Gel.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (41, 6, 'Busakan dengan air dan usapkan pada wajah yang basah. ', 'Foam JF Anti Acne Facial Foam with water and apply to damp face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (42, 6, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (43, 6, 'Bilas hingga bersih. ', 'Wash face thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (44, 6, 'Untuk hasil optimal, lanjutkan dengan penggunaan JF Anti Acne Spot Care Gel', 'For best result, also apply JF Anti Acne Gel.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (45, 6, 'Busakan dengan air dan usapkan pada wajah yang basah. ', 'Foam JF Anti Acne Facial Foam with water and apply to damp face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (46, 6, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (47, 6, 'Bilas hingga bersih. ', 'Wash face thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (48, 6, 'Untuk hasil optimal, lanjutkan dengan penggunaan JF Anti Acne Spot Care Gel', 'For best result, also apply JF Anti Acne Gel.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (49, 7, 'Busakan dengan air dan usapkan pada wajah yang basah.', 'Foam JF Acne Protect Facial Foam with water and apply to damp face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (50, 7, 'Busakan dengan air dan usapkan pada wajah yang basah.', 'Foam JF Acne Protect Facial Foam with water and apply to damp face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (51, 7, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (52, 7, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (53, 7, 'Bilas hingga bersih. ', 'Wash face thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (54, 7, 'Bilas hingga bersih. ', 'Wash face thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (55, 8, 'Oleskan secara teratur minimal 2 kali sehari pada jerawat. ', 'Apply on acne area regularly at least 2 times a day.\r\n', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (56, 8, 'Oleskan secara teratur minimal 2 kali sehari pada jerawat. ', 'Apply on acne area regularly at least 2 times a day.\r\n', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (57, 8, 'Untuk hasil lebih optimal, gunakan JF Anti Acne Cleanser Bar atau Facial Foam. ', ' For best result, use JF Anti Acne Cleanser Bar or Facial Foam prior to applying.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (58, 8, 'Untuk hasil lebih optimal, gunakan JF Anti Acne Cleanser Bar atau Facial Foam. ', ' For best result, use JF Anti Acne Cleanser Bar or Facial Foam prior to applying.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (59, 8, 'Hindari kontak dengan mata. ', 'Avoid contact with eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (60, 8, 'Hindari kontak dengan mata. ', 'Avoid contact with eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (61, 8, 'Simpan pada suhu di bawah 30 C.', 'Store at temperatures below 30°C.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (62, 8, 'Simpan pada suhu di bawah 30 C.', 'Store at temperatures below 30°C.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (63, 9, 'Oleskan secara teratur minimal 2 kali sehari pada noda bekas jerawat. ', 'Apply on acne area regularly at least 2 times a day.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (64, 9, 'Oleskan secara teratur minimal 2 kali sehari pada noda bekas jerawat. ', 'Apply on acne area regularly at least 2 times a day.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (65, 9, 'Untuk hasil lebih optimal, gunakan JF Acne Spot Care Cleanser Bar atau Facial Foam.  ', 'For best result, use JF Anti Acne Cleanser Bar or Facial Foam prior to applying.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (66, 9, 'Untuk hasil lebih optimal, gunakan JF Acne Spot Care Cleanser Bar atau Facial Foam.  ', 'For best result, use JF Anti Acne Cleanser Bar or Facial Foam prior to applying.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (67, 9, 'Hindari kontak dengan mata.', 'Avoid contact with eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (68, 9, 'Hindari kontak dengan mata.', 'Avoid contact with eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (69, 9, 'Simpan pada suhu di bawah 30 C.', 'Store at temperatures below 30°C.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (70, 9, 'Simpan pada suhu di bawah 30 C.', 'Store at temperatures below 30°C.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (71, 10, ' Tarik JF Acne Series Wet Wipes beberapa lembar untuk membersihkan wajah setelah berkendara, olahraga atau melakukan beragam aktivitas lainnya.', 'Pull out several sheets of JF Acne Series Wet Wipes to cleanse your face after driving, working out, or engaging in other activities.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (72, 10, ' Tarik JF Acne Series Wet Wipes beberapa lembar untuk membersihkan wajah setelah berkendara, olahraga atau melakukan beragam aktivitas lainnya.', 'Pull out several sheets of JF Acne Series Wet Wipes to cleanse your face after driving, working out, or engaging in other activities.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (73, 10, 'Cocok digunakan untuk mengeringkan wajah setelah dibersihkan dengan sabun JF.', 'Suitable for drying the face after cleansing with JF soap.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (74, 10, 'Cocok digunakan untuk mengeringkan wajah setelah dibersihkan dengan sabun JF.', 'Suitable for drying the face after cleansing with JF soap.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (75, 10, 'Dapat dipakai sebelum tidur, setelah berkendara, berolahraga, dan beraktivitas.', 'Can be used before bedtime, after driving, exercising, and engaging in activities.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (76, 10, 'Dapat dipakai sebelum tidur, setelah berkendara, berolahraga, dan beraktivitas.', 'Can be used before bedtime, after driving, exercising, and engaging in activities.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (77, 11, 'Busakan dengan air dan usapkan pada tubuh yang basah. ', ' Foam the soap with water and apply it to the wet body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (78, 11, ' Busakan dengan air dan usapkan pada tubuh yang basah. ', ' Foam the soap with water and apply it to the wet body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (79, 11, 'Hindari bagian mata. ', 'Avoid the eye area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (80, 11, 'Hindari bagian mata. ', 'Avoid the eye area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (81, 11, 'Bilas hingga bersih. ', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (82, 11, 'Bilas hingga bersih. ', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (83, 12, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water\r\n', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (84, 12, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water\r\n', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (85, 12, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (86, 12, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (87, 12, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (88, 12, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (89, 12, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (90, 12, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (91, 13, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (92, 13, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (93, 13, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (94, 13, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (95, 13, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (96, 13, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (97, 13, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (98, 13, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (99, 14, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (100, 14, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (101, 14, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (102, 14, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (103, 14, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (104, 14, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (105, 14, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (106, 14, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (107, 15, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (108, 15, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (109, 15, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (110, 15, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (111, 15, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (112, 15, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (113, 15, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (114, 15, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (115, 16, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (116, 16, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (117, 16, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (118, 16, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (119, 16, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (120, 16, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (121, 16, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (122, 16, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (123, 17, 'Busakan dengan air dan usapkan pada tubuh yang basah. ', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (124, 17, 'Busakan dengan air dan usapkan pada tubuh yang basah. ', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (125, 17, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (126, 17, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (127, 17, 'Bilas hingga bersih. ', 'Rinse thoroughly. ', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (128, 17, 'Bilas hingga bersih. ', 'Rinse thoroughly. ', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (129, 18, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (130, 18, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (131, 18, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (132, 18, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (133, 18, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (134, 18, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (135, 18, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (136, 18, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (137, 19, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (138, 19, 'Tuangkan sabun pada telapak tangan dan busakan dengan air.', 'Foam the soap with water', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (139, 19, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (140, 19, 'Usapkan pada seluruh tubuh.', 'Apply to the wet body', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (141, 19, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (142, 19, 'Hindari bagian mata. ', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (143, 19, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (144, 19, 'Bilas hingga bersih. ', 'Rinse thoroughly', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (145, 20, 'Basahi tangan sebelum menuangkan sabun', 'Wet hands with clean water hand before pouring the soap.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (146, 20, 'Basahi tangan sebelum menuangkan sabun', 'Wet hands with clean water hand before pouring the soap.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (147, 20, 'Tekan 1 kali, gosok hingga berbusa pada seluruh tangan, lalu bersihkan sela-sela jari dan kuku. ', 'Pump once, rub hands together until it lathers, clean between the fingers and nails.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (148, 20, 'Tekan 1 kali, gosok hingga berbusa pada seluruh tangan, lalu bersihkan sela-sela jari dan kuku. ', 'Pump once, rub hands together until it lathers, clean between the fingers and nails.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (149, 20, 'Bilas dengan air bersih.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (150, 20, 'Bilas dengan air bersih.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (151, 20, 'Jika terkena mata, bilas dengan air.', 'Avoid eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (152, 20, 'Jika terkena mata, bilas dengan air.', 'Avoid eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (153, 21, 'Tuang pada telapak tangan, gosok dan ratakan hingga ke sela jari sampai kering. ', 'Pour on both hands, rub both hands and between fingers until dry. ', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (154, 21, 'Tuang pada telapak tangan, gosok dan ratakan hingga ke sela jari sampai kering. ', 'Pour on both hands, rub both hands and between fingers until dry. ', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (155, 21, 'Produk ini mudah terbakar sehingga jauhkan dari api', 'This product is flammable. Keep away from fire.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (156, 21, 'Produk ini mudah terbakar sehingga jauhkan dari api', 'This product is flammable. Keep away from fire.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (157, 21, 'Jika terkena mata, bilas dengan air. P', 'If it comes into contact with eyes, rinse with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (158, 21, 'Jika terkena mata, bilas dengan air. P', 'If it comes into contact with eyes, rinse with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (159, 21, 'Pemakaian untuk anak-anak harus di bawah pengawasan orang dewasa.', 'Usage for children should be under adult supervision.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (160, 21, 'Pemakaian untuk anak-anak harus di bawah pengawasan orang dewasa.', 'Usage for children should be under adult supervision.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (161, 22, 'Semprotkan pada telapak tangan dan di sela-sela jari hingga kering.', 'Spray to both palm hands, and between fingers.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (162, 22, 'Semprotkan pada telapak tangan dan di sela-sela jari hingga kering.', 'Spray to both palm hands, and between fingers.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (163, 23, 'Busakan Oilum Hydrating Care Cleansing Bar dengan air.', 'Lather Oilum Hydrating Care Cleansing Bar with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (164, 23, 'Busakan Oilum Hydrating Care Cleansing Bar dengan air.', 'Lather Oilum Hydrating Care Cleansing Bar with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (165, 23, 'Usapkan pada kulit dengan lembut, dan bilas hingga tidak ada busa atau sabun yang tersisa.', 'Rub gently to body skin, and rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (166, 23, 'Usapkan pada kulit dengan lembut, dan bilas hingga tidak ada busa atau sabun yang tersisa.', 'Rub gently to body skin, and rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (167, 23, 'Bilas hingga tidak ada busa dan sisa sabun.\r\n', 'If it comes to contact eyes, rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (168, 23, 'Bilas hingga tidak ada busa dan sisa sabun.\r\n', 'If it comes to contact eyes, rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (170, 24, 'Busakan Oilum Hydrating Care Cleansing Bar dengan air.', 'Lather Oilum Hydrating Care Cleansing Bar  with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (171, 24, 'Busakan Oilum Hydrating Care Cleansing Bar dengan air.', 'Lather Oilum Hydrating Care Cleansing Bar  with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (172, 24, 'Usapkan pada kulit dengan lembut, dan bilas hingga tidak ada busa atau sabun yang tersisa.', 'Rub gently to body skin, and rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (173, 24, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.\r\nUsapkan pada kulit dengan lembut, dan bilas hingga tidak ada busa atau sabun yang tersisa.', 'Rub gently to body skin, and rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (174, 24, 'Bilas hingga tidak ada busa dan sisa sabun.\r\nJika terkena mata, bilas dengan air hingga bersih.', 'If it comes to contact eyes, rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (175, 24, 'Jika terkena mata, bilas dengan air hingga bersih.', 'If it comes to contact eyes, rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (176, 25, 'Tuangkan OILUM Hydrating Care Body Lotion pada telapak tangan.', 'Pour OILUM Hydrating Care Body Lotion onto palm hands.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (177, 25, 'Tuangkan OILUM Hydrating Care Body Lotion pada telapak tangan.', 'Pour OILUM Hydrating Care Body Lotion onto palm hands.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (178, 25, 'Usapkan pada seluruh tubuh setelah mandi.', 'Apply to body after bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (179, 25, 'Usapkan pada seluruh tubuh setelah mandi.', 'Apply to body after bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (180, 26, 'Oleskan OILUM Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Body Butter to body skin or dry skin area', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (181, 26, 'Oleskan OILUM Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Body Butter to body skin or dry skin area', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (182, 26, 'Untuk hasil maksimal gunakan pada pagi dan malam hari. ', 'For best result, apply in the morning and at night.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (183, 26, 'Untuk hasil maksimal gunakan pada pagi dan malam hari. ', 'For best result, apply in the morning and at night.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (184, 27, 'Oleskan OILUM Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Body Butter to body skin or dry skin area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (185, 27, 'Oleskan OILUM Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Body Butter to body skin or dry skin area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (186, 27, 'Untuk hasil maksimal gunakan pada pagi dan malam hari. ', 'For best result, apply in the morning and at night.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (187, 27, 'Untuk hasil maksimal gunakan pada pagi dan malam hari. ', 'For best result, apply in the morning and at night.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (188, 28, 'Busakan sabun dengan air dan usapkan pada kulit dengan lembut.', 'Wet the soap with water and gently apply it to the skin.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (189, 28, 'Busakan sabun dengan air dan usapkan pada kulit dengan lembut.', 'Wet the soap with water and gently apply it to the skin.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (190, 28, 'Bilas dengan air hingga bersih dan tidak ada sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (191, 28, 'Bilas dengan air hingga bersih dan tidak ada sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (192, 28, 'Jika terkena mata, bilas dengan air hingga bersih.', 'Jika terkena mata, bilas dengan air hingga bersih.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (193, 28, 'Jika terkena mata, bilas dengan air hingga bersih.', 'Jika terkena mata, bilas dengan air hingga bersih.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (194, 29, 'Tuangkan Oilum Brightening Care Body Lotion pada telapan tangan.', 'Pour Oilum Brightening Care Body Lotion onto palm hands.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (195, 29, 'Tuangkan Oilum Brightening Care Body Lotion pada telapan tangan.', 'Pour Oilum Brightening Care Body Lotion onto palm hands.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (196, 29, 'Usapkan pada seluruh tubuh setelah mandi.', 'Apply to body after bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (197, 29, 'Usapkan pada seluruh tubuh setelah mandi.', 'Apply to body after bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (198, 29, 'Oleskan OILUM Brightening Care Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Brightening Care Body Butter to body skin or dry skin area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (199, 29, 'Oleskan OILUM Brightening Care Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Brightening Care Body Butter to body skin or dry skin area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (200, 29, 'Untuk hasil maksimal gunakan pada pagi dan malam hari.', 'For best result, apply in the morning and at night.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (201, 29, 'Untuk hasil maksimal gunakan pada pagi dan malam hari.', 'For best result, apply in the morning and at night.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (202, 30, 'Oleskan OILUM Brightening Care Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Brightening Care Body Butter to body skin or dry skin area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (203, 30, 'Oleskan OILUM Brightening Care Body Butter pada tubuh atau bagian kulit yang kering.', 'Apply OILUM Brightening Care Body Butter to body skin or dry skin area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (204, 30, 'Untuk hasil maksimal gunakan pada pagi dan malam hari.', 'For best result, apply in the morning and at night.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (205, 30, 'Untuk hasil maksimal gunakan pada pagi dan malam hari.', 'For best result, apply in the morning and at night.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (206, 31, 'Basahkan wajah dengan air, lalu usapkan OILUM Facial Bar di seluruh area wajah', 'Wet face and apply OILUM Facial Bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (207, 31, 'Basahkan wajah dengan air, lalu usapkan OILUM Facial Bar di seluruh area wajah', 'Wet face and apply OILUM Facial Bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (208, 31, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (209, 31, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (210, 32, 'Setelah menggunakan Oilum Facial Serum, oleskan Oilum Day Cream pada wajah.', 'After applying Oilum Facial Serum, apply Oilum Day Cream.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (211, 32, 'Setelah menggunakan Oilum Facial Serum, oleskan Oilum Day Cream pada wajah.', 'After applying Oilum Facial Serum, apply Oilum Day Cream.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (212, 32, 'Gunakan pada pagi hari sebelum beraktivitas, terutama untuk aktivitas luar ruangan.', 'Use in the morning before starting activities, particularly outdoor activities.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (213, 32, 'Gunakan pada pagi hari sebelum beraktivitas, terutama untuk aktivitas luar ruangan.', 'Use in the morning before starting activities, particularly outdoor activities.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (214, 33, 'Setelah menggunakan Oilum Facial Serum, oleskan Oilum Night Cream pada wajah.', 'After applying Oilum Facial Serum, apply Oilum Night Cream.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (215, 33, 'Setelah menggunakan Oilum Facial Serum, oleskan Oilum Night Cream pada wajah.', 'After applying Oilum Facial Serum, apply Oilum Night Cream.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (216, 33, 'Gunakan pada malam hari.', 'Use at night.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (217, 33, 'Gunakan pada malam hari.', 'Use at night.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (218, 34, 'Tuangkan beberapa tetes Oilum Facial Serum pada telapak tangan.', 'Pour a few drops of Oilum Facial Serum onto a palm hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (219, 34, 'Tuangkan beberapa tetes Oilum Facial Serum pada telapak tangan.', 'Pour a few drops of Oilum Facial Serum onto a palm hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (220, 34, 'Usapkan pada wajah secara merata.', 'Apply to face evenly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (221, 34, 'Usapkan pada wajah secara merata.', 'Apply to face evenly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (222, 34, 'Gunakan pada pagi dan malam hari sebelum menggunakan Oilum Day Cream dan Night Cream.', 'Use in the morning and at night before applying Oilum Day Cream dan Night Cream.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (223, 34, 'Gunakan pada pagi dan malam hari sebelum menggunakan Oilum Day Cream dan Night Cream.', 'Use in the morning and at night before applying Oilum Day Cream dan Night Cream.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (224, 35, 'Basahkan wajah dengan air, lalu busakan OILUM Facial Foam di seluruh area wajah.', 'Wet face and apply OILUM Facial Foam.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (225, 35, 'Basahkan wajah dengan air, lalu busakan OILUM Facial Foam di seluruh area wajah.', 'Wet face and apply OILUM Facial Foam.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (226, 35, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (227, 35, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (228, 36, 'Basahkan wajah dengan air, lalu busakan OILUM Brightening Care Facial Bar di seluruh area wajah.', 'Wet face and apply OILUM Brightening Care Facial Bar.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (229, 36, 'Basahkan wajah dengan air, lalu busakan OILUM Brightening Care Facial Bar di seluruh area wajah.', 'Wet face and apply OILUM Brightening Care Facial Bar.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (230, 36, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (231, 36, 'Bilas dengan air hingga bersih.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (232, 37, 'Oleskan Oilum Day Cream pada wajah secara merata.', 'Apply Oilum Day Cream on face evenly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (233, 37, 'Oleskan Oilum Day Cream pada wajah secara merata.', 'Apply Oilum Day Cream on face evenly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (234, 37, 'Gunakan pada pagi hari setelah mengaplikasikan Oilum Facial Serum.', 'Use in the morning after applying Oilum Facial Serum.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (235, 37, 'Gunakan pada pagi hari setelah mengaplikasikan Oilum Facial Serum.', 'Use in the morning after applying Oilum Facial Serum.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (236, 38, 'Oleskan Oilum Night Cream pada wajah secara merata.', 'Apply Oilum Night Cream on face evenly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (237, 38, 'Oleskan Oilum Night Cream pada wajah secara merata.', 'Apply Oilum Night Cream on face evenly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (238, 38, 'Gunakan pada malam hari setelah mengaplikasikan Oilum Facial Serum.', 'Use at night after applying Oilum Facial Serum.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (239, 38, 'Gunakan pada malam hari setelah mengaplikasikan Oilum Facial Serum.', 'Use at night after applying Oilum Facial Serum.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (240, 39, 'Tuangkan Oilum Brightening Care Facial Serum pada telapak tangan.', 'Pour Oilum Brightening Care Facial Serum on a palm hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (241, 39, 'Tuangkan Oilum Brightening Care Facial Serum pada telapak tangan.', 'Pour Oilum Brightening Care Facial Serum on a palm hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (242, 39, 'Oleskan pada wajah secara merata pada pagi dan malam hari sebelum menggunakan Oilum Brightening Care Day Cream dan Night Cream.', 'Apply on the face evenly in the morning and at night before applying Oilum Brightening Oilum Brightening Care Day Cream dan Night Cream.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (243, 39, 'Oleskan pada wajah secara merata pada pagi dan malam hari sebelum menggunakan Oilum Brightening Care Day Cream dan Night Cream.', 'Apply on the face evenly in the morning and at night before applying Oilum Brightening Oilum Brightening Care Day Cream dan Night Cream.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (244, 40, 'Oleskan secara merata pada bagian wajah sebelum beraktivitas.', 'Apply evenly to face before doing activities.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (245, 40, 'Oleskan secara merata pada bagian wajah sebelum beraktivitas.', 'Apply evenly to face before doing activities.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (246, 40, 'Dapat juga digunakan sebelum memakai bedak atau foundation.', 'Can be used before applying makeup.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (247, 40, 'Dapat juga digunakan sebelum memakai bedak atau foundation.', 'Can be used before applying makeup.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (248, 40, 'Gunakan kembali secara teratur untuk menjaga perlindungan terhadap sinar UV khususnya setelah berkeringat, berenang, atau membilas wajah.', 'Use regularly to protect facial skin from UV exposure, particularly after sweating, swimming or washing face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (249, 40, 'Gunakan kembali secara teratur untuk menjaga perlindungan terhadap sinar UV khususnya setelah berkeringat, berenang, atau membilas wajah.', 'Use regularly to protect facial skin from UV exposure, particularly after sweating, swimming or washing face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (250, 41, 'Gunakan saat pagi dan malam hari pada area kulit sekitar mata yang telah dibersihkan.', 'Apply in the morning and at night on the skin around the eyes that has been cleansed.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (251, 41, 'Gunakan saat pagi dan malam hari pada area kulit sekitar mata yang telah dibersihkan.', 'Apply in the morning and at night on the skin around the eyes that has been cleansed.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (252, 41, 'Hindari kontak langsung dengan mata.', 'Avoid touching the eyes.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (253, 41, 'Hindari kontak langsung dengan mata.', 'Avoid touching the eyes.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (254, 42, 'Oleskan Soft U Derm Intensive Hydro-Protect secara merata pada lengan, kaki, dan bagian kulit kering lainnya.', 'Apply Soft U Derm Intensive Hydro-Protect evenly on your arms, legs, and other dry skin areas.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (255, 42, 'Oleskan Soft U Derm Intensive Hydro-Protect secara merata pada lengan, kaki, dan bagian kulit kering lainnya.', 'Apply Soft U Derm Intensive Hydro-Protect evenly on your arms, legs, and other dry skin areas.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (256, 42, 'Untuk hasil maksimal gunakan minimal dua kali sehari.', 'For best result, use at least twice a day.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (257, 42, 'Untuk hasil maksimal gunakan minimal dua kali sehari.', 'For best result, use at least twice a day.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (258, 43, 'Sebelum menggunakan Ressal Acne Lotion, bersihkan wajah terlebih dahulu.', 'Cleanse face prior to applying.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (259, 43, 'Sebelum menggunakan Ressal Acne Lotion, bersihkan wajah terlebih dahulu.', 'Cleanse face prior to applying.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (260, 43, 'Tuangkan losion pada kapas bersih kemudian oleskan sebesar butiran jagung pada seluruh wajah terutama bagian-bagian yang berjerawat.', 'Pour the lotion onto a clean cotton pad, apply a drop to several parts of your face, particularly the acne-prone areas.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (261, 43, 'Tuangkan losion pada kapas bersih kemudian oleskan sebesar butiran jagung pada seluruh wajah terutama bagian-bagian yang berjerawat.', 'Pour the lotion onto a clean cotton pad, apply a drop to several parts of your face, particularly the acne-prone areas.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (262, 43, 'Tunggu hingga meresap, jangan dibilas.', 'Leave to dry, do not rinse.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (263, 43, 'Tunggu hingga meresap, jangan dibilas.', 'Leave to dry, do not rinse.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (264, 43, 'Losion dapat digunakan setiap habis mandi.', 'Best used after bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (265, 43, 'Losion dapat digunakan setiap habis mandi.', 'Best used after bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (266, 44, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (267, 44, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (268, 44, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (269, 44, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (270, 45, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (271, 45, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (272, 45, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (273, 45, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (274, 46, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (275, 46, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (276, 46, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (277, 46, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (278, 47, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (279, 47, 'Setelah mandi, taburkan bedak Caladine ke telapak tangan.', 'After bathing, pour Caladine powder onto the palm of your hand.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (280, 47, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (281, 47, 'Usapkan ke seluruh bagian tubuh.', 'Apply to all over body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (282, 48, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (283, 48, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (284, 48, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (285, 48, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (286, 49, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (287, 49, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (288, 49, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (289, 49, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (290, 50, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (291, 50, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (292, 50, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (293, 50, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (294, 51, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (295, 51, 'Setelah mandi, tuangkan bedak Caladine Powder Soft Comfort ke telapak tangan.', 'After bathing, pour Caladine Soft Comfort Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (296, 51, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (297, 51, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (298, 52, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (299, 52, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (300, 52, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (301, 52, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (302, 53, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (303, 53, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (304, 53, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (305, 53, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (306, 54, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (307, 54, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (308, 54, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (309, 54, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (310, 55, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (311, 55, 'Setelah mandi, tuangkan bedak Caladine Powder Active Fresh ke telapak tangan.', 'After bathing, pour Caladine Active Fresh Powder onto your palm.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (312, 55, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (313, 55, 'Usapkan ke seluruh bagian tubuh, terutama bagian yang mudah terserang biang keringat.', 'Apply it to your entire body, especially areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (314, 56, 'Sebelum pemakaian pastikan kulit sudah dibersihkan.', 'Cleanse the skin prior to applying.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (315, 56, 'Sebelum pemakaian pastikan kulit sudah dibersihkan.', 'Cleanse the skin prior to applying.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (316, 56, 'Tuangkan Caladine Adult Powder secukupnya ke telapak tangan kemudian diusapkan ke seluruh area badan dan punggung, terutama pada bagian yang sering terserang biang keringat.', 'Pour an adequate amount of Caladine Adult Powder onto your palm and then apply to entire body and back, especially in areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (317, 56, 'Tuangkan Caladine Adult Powder secukupnya ke telapak tangan kemudian diusapkan ke seluruh area badan dan punggung, terutama pada bagian yang sering terserang biang keringat.', 'Pour an adequate amount of Caladine Adult Powder onto your palm and then apply to entire body and back, especially in areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (318, 56, 'Untuk hasil maksimal, gunakan 2 kali sehari setelah mandi.', 'For best result, use twice a day after bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (319, 56, 'Untuk hasil maksimal, gunakan 2 kali sehari setelah mandi.', 'For best result, use twice a day after bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (320, 56, 'Pemakaian khusus untuk orang dewasa.', 'For adults only.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (321, 56, 'Pemakaian khusus untuk orang dewasa.', 'For adults only.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (322, 57, 'Sebelum pemakaian pastikan kulit sudah dibersihkan.', 'Cleanse the skin prior to applying.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (323, 57, 'Sebelum pemakaian pastikan kulit sudah dibersihkan.', 'Cleanse the skin prior to applying.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (324, 57, 'Tuangkan Caladine Adult Powder secukupnya ke telapak tangan kemudian diusapkan ke seluruh area badan dan punggung, terutama pada bagian yang sering terserang biang keringat.', 'Pour an adequate amount of Caladine Adult Powder onto your palm and then apply to entire body and back, especially in areas prone to heat rash.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (325, 57, 'Tuangkan Caladine Adult Powder secukupnya ke telapak tangan kemudian diusapkan ke seluruh area badan dan punggung, terutama pada bagian yang sering terserang biang keringat.', 'Pour an adequate amount of Caladine Adult Powder onto your palm and then apply to entire body and back, especially in areas prone to heat rash.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (326, 57, 'Untuk hasil maksimal, gunakan 2 kali sehari setelah mandi.', 'For best result, use twice a day after bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (327, 57, 'Untuk hasil maksimal, gunakan 2 kali sehari setelah mandi.', 'For best result, use twice a day after bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (328, 57, 'Pemakaian khusus untuk orang dewasa.', 'For adults only.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (329, 57, 'Pemakaian khusus untuk orang dewasa.', 'For adults only.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (330, 58, 'Bersihkan kulit yang kemerahan karena gatal yang diakibatkan oleh alergi dengan air hangat.', 'Clean the skin rash caused by allergies with warm water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (331, 58, 'Bersihkan kulit yang kemerahan karena gatal yang diakibatkan oleh alergi dengan air hangat.', 'Clean the skin rash caused by allergies with warm water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (332, 58, 'Setelah dibersihkan, keringkan dengan lap atau handuk.', 'After cleaning, pat dry with a towel.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (333, 58, 'Setelah dibersihkan, keringkan dengan lap atau handuk.', 'After cleaning, pat dry with a towel.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (334, 58, 'Oleskan Caladine Lotion secara merata ke bagian yang terkena gatal atau kemerahan akibat alergi.', 'Apply Caladine Lotion evenly to the areas affected by itching or rash due to allergies.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (335, 58, 'Oleskan Caladine Lotion secara merata ke bagian yang terkena gatal atau kemerahan akibat alergi.', 'Apply Caladine Lotion evenly to the areas affected by itching or rash due to allergies.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (336, 58, 'Pemakaian hanya saat gatal akibat alergi. Dianjurkan tidak untuk digunakan sehari-hari.', 'Use only when itching occurs due to allergies. Not for daily use.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (337, 58, 'Pemakaian hanya saat gatal akibat alergi. Dianjurkan tidak untuk digunakan sehari-hari.', 'Use only when itching occurs due to allergies. Not for daily use.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (338, 59, 'Bersihkan kulit yang kemerahan karena gatal yang diakibatkan oleh alergi dengan air hangat.', 'Clean the skin rash caused by allergies with warm water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (339, 59, 'Bersihkan kulit yang kemerahan karena gatal yang diakibatkan oleh alergi dengan air hangat.', 'Clean the skin rash caused by allergies with warm water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (340, 59, 'Setelah dibersihkan, keringkan dengan lap atau handuk.', 'After cleaning, pat dry with a towel.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (341, 59, 'Setelah dibersihkan, keringkan dengan lap atau handuk.', 'After cleaning, pat dry with a towel.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (342, 59, 'Oleskan Caladine Lotion secara merata ke bagian yang terkena gatal atau kemerahan akibat alergi.', 'Apply Caladine Lotion evenly to the areas affected by itching or rash due to allergies.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (343, 59, 'Oleskan Caladine Lotion secara merata ke bagian yang terkena gatal atau kemerahan akibat alergi.', 'Apply Caladine Lotion evenly to the areas affected by itching or rash due to allergies.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (344, 59, 'Pemakaian hanya saat gatal akibat alergi. Dianjurkan tidak untuk digunakan sehari-hari.', 'Use only when itching occurs due to allergies. Not for daily use.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (345, 59, 'Pemakaian hanya saat gatal akibat alergi. Dianjurkan tidak untuk digunakan sehari-hari.', 'Use only when itching occurs due to allergies. Not for daily use.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (346, 60, 'Bersihkan bagian kulit yang gatal, lalu oleskan Caladine Lotion Fresh and Calming 2-4 kali sehari.', 'Clean the rash area, then apply Caladine Lotion Fresh and Calming 2-4 times a day.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (347, 60, 'Bersihkan bagian kulit yang gatal, lalu oleskan Caladine Lotion Fresh and Calming 2-4 kali sehari.', 'Clean the rash area, then apply Caladine Lotion Fresh and Calming 2-4 times a day.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (348, 60, 'Untuk hasil maksimal gunakan setelah mandi pagi dan shore hari.', 'For best result, apply after morning and evening showers.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (349, 60, 'Untuk hasil maksimal gunakan setelah mandi pagi dan shore hari.', 'For best result, apply after morning and evening showers.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (350, 60, 'Dapat digunakan sehari-hari secara rutin.', 'For daily use.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (351, 60, 'Dapat digunakan sehari-hari secara rutin.', 'For daily use.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (352, 61, 'Bersihkan area yang terkena gatal dan kemerahan akibat gigitan serangga (nyamuk, semut, dan lain-lain) dengan air hangat.', 'Clean the area affected by itching and rash due to insect bites (mosquitoes, ants, and others) with warm water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (353, 61, 'Bersihkan area yang terkena gatal dan kemerahan akibat gigitan serangga (nyamuk, semut, dan lain-lain) dengan air hangat.', 'Clean the area affected by itching and rash due to insect bites (mosquitoes, ants, and others) with warm water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (354, 61, 'Keringkan dengan handuk.', 'Dry with towel.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (355, 61, 'Keringkan dengan handuk.', 'Dry with towel.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (356, 61, 'Oleskan Caladine Cream hanya dibagian bentol gatal kemerahan.', 'Apply Caladine Cream only to the itchy red bumps.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (357, 61, 'Oleskan Caladine Cream hanya dibagian bentol gatal kemerahan.', 'Apply Caladine Cream only to the itchy red bumps.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (358, 62, 'Semprotkan Caladine Mosquito Lotion Repellent ke permukaan kulit bagian tangan dan kaki. Hindari pemakaian di area waja (terutama mata dan mulut).', 'Spray Caladine Mosquito Lotion Repellent on hands and feet skin. Avoid applying to the face area, especially around the eyes and mouth.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (359, 62, 'Semprotkan Caladine Mosquito Lotion Repellent ke permukaan kulit bagian tangan dan kaki. Hindari pemakaian di area waja (terutama mata dan mulut).', 'Spray Caladine Mosquito Lotion Repellent on hands and feet skin. Avoid applying to the face area, especially around the eyes and mouth.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (360, 62, 'Tunggu hingga menyerap, jangan disentuh dengan jari atau telapak tangan, apabila tersentuh, cuci tangan dengan air dan sabun.', 'Allow it to absorb; do not touch it with your fingers or palms. If touched, wash your hands with soap and water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (361, 62, 'Tunggu hingga menyerap, jangan disentuh dengan jari atau telapak tangan, apabila tersentuh, cuci tangan dengan air dan sabun.', 'Allow it to absorb; do not touch it with your fingers or palms. If touched, wash your hands with soap and water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (362, 63, 'Tuangkan Caladine Gel ke telapak tangan dan oleskan secara merata dibagian tubuh, tangan, kaki yang terasa gatal.', '', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (363, 63, 'Tuangkan Caladine Gel ke telapak tangan dan oleskan secara merata dibagian tubuh, tangan, kaki yang terasa gatal.', '', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (364, 63, 'Produk dapat digunakan di permukaan kulit wajah.', 'Pour Caladine Gel onto the palm of your hand and apply evenly on the body, hands, and feet that feel itchy.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (365, 63, 'Produk dapat digunakan di permukaan kulit wajah.', 'Pour Caladine Gel onto the palm of your hand and apply evenly on the body, hands, and feet that feel itchy.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (366, 64, 'Busakan sabun dengan air kemudian usapkan ke seluruh tubuh bayi.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (367, 64, 'Busakan sabun dengan air kemudian usapkan ke seluruh tubuh bayi.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (368, 64, 'Bilas hingga bersih supaya sampai tidak ada sisa sabun yang menempel pada kulit bayi.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (369, 64, 'Bilas hingga bersih supaya sampai tidak ada sisa sabun yang menempel pada kulit bayi.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (370, 64, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (371, 64, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (372, 65, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (373, 65, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (374, 65, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (375, 65, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (376, 65, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (377, 65, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (378, 66, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (379, 66, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (380, 66, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (381, 66, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (382, 66, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (383, 66, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (384, 67, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (385, 67, 'Busakan sabun Caladine Baby Liquid dengan air.', 'Foam the soap with water, then apply it to the baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (386, 67, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (387, 67, 'Usapkan sabun ke seluruh tubuh bayi, bilas sampai bersih hingga tidak ada sisa sabun yang menempel di kulit.', 'Rinse thoroughly and make sure no soap residue left.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (388, 67, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (389, 67, 'Hindari sabun menyentuh bagian mata, telinga, dan mulut.', 'Avoid eyes, ears, and mouth.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (390, 68, 'Tuangkan bedakCaladine Baby Powder ke telapak tangan secukupnya dan usapkan ke seluruh tubuh bayi.', 'Pour an adequate amount of Caladine Baby Powder onto your palm and apply to baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (391, 68, 'Tuangkan bedakCaladine Baby Powder ke telapak tangan secukupnya dan usapkan ke seluruh tubuh bayi.', 'Pour an adequate amount of Caladine Baby Powder onto your palm and apply to baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (392, 68, 'Hindari pemakaian pada area kelamin, dan wajah bayi.', 'Avoid genital area and face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (393, 68, 'Hindari pemakaian pada area kelamin, dan wajah bayi.', 'Avoid genital area and face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (394, 68, 'Dianjurkan untuk menggunakan bedak setelah mandi.', 'Use the powder after bathing for the best result.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (395, 68, 'Dianjurkan untuk menggunakan bedak setelah mandi.', 'Use the powder after bathing for the best result.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (396, 69, 'Tuangkan bedakCaladine Baby Powder ke telapak tangan secukupnya dan usapkan ke seluruh tubuh bayi.', 'Pour an adequate amount of Caladine Baby Powder onto your palm and apply to baby\'s entire body.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (397, 69, 'Tuangkan bedakCaladine Baby Powder ke telapak tangan secukupnya dan usapkan ke seluruh tubuh bayi.', 'Pour an adequate amount of Caladine Baby Powder onto your palm and apply to baby\'s entire body.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (398, 69, 'Hindari pemakaian pada area kelamin, dan wajah bayi.', 'Avoid genital area and face.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (399, 69, 'Hindari pemakaian pada area kelamin, dan wajah bayi.', 'Avoid genital area and face.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (400, 69, 'Dianjurkan untuk menggunakan bedak setelah mandi.', 'Use the powder after bathing for the best result.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (401, 69, 'Dianjurkan untuk menggunakan bedak setelah mandi.', 'Use the powder after bathing for the best result.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (402, 70, 'Sebelum gunakan Caladine Baby Liquid Powder, pastikan kulit tubuh bayi telah bersih.', 'Clean baby\'s body before using Caladine Baby Liquid Powder.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (403, 70, 'Sebelum gunakan Caladine Baby Liquid Powder, pastikan kulit tubuh bayi telah bersih.', 'Clean baby\'s body before using Caladine Baby Liquid Powder.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (404, 70, 'Tuangkan Caladine Baby Liquid Powder secukupnya ke telapak tangan dan oleskan pada seluruh tubuh bayi kecuali area mata, mulut, dan telinga.', 'Pour an adequate amount of Caladine Baby Liquid Powder onto palm and apply to baby\'s entire body Avoid eyes, mouth, and ears.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (405, 70, 'Tuangkan Caladine Baby Liquid Powder secukupnya ke telapak tangan dan oleskan pada seluruh tubuh bayi kecuali area mata, mulut, dan telinga.', 'Pour an adequate amount of Caladine Baby Liquid Powder onto palm and apply to baby\'s entire body Avoid eyes, mouth, and ears.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (406, 70, 'Pemakaian harian atau setiap saat apabila diperlukan.', 'Use daily or whenever necessary.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (407, 70, 'Pemakaian harian atau setiap saat apabila diperlukan.', 'Use daily or whenever necessary.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (408, 71, 'Sebelum menggunakan Caladine Baby Rash Cream, bersihkan kulit bayi di area yang menggunakan popok.', 'Before using Caladine Baby Rash Cream, clean baby\'s skin in the diaper area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (409, 71, 'Sebelum menggunakan Caladine Baby Rash Cream, bersihkan kulit bayi di area yang menggunakan popok.', 'Before using Caladine Baby Rash Cream, clean baby\'s skin in the diaper area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (410, 71, 'Setelah bersih, tuangkan Caladine Baby Rash Cream secukupnya ke telapak tangan kemudian oleskan ke area yang tertutup popok.', 'After cleaning, pour an adequate amount of Caladine Baby Rash Cream onto palm and apply it to the diaper-covered area.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (411, 71, 'Setelah bersih, tuangkan Caladine Baby Rash Cream secukupnya ke telapak tangan kemudian oleskan ke area yang tertutup popok.', 'After cleaning, pour an adequate amount of Caladine Baby Rash Cream onto palm and apply it to the diaper-covered area.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (412, 71, 'Biarkan sebentar hingga krim meresap pada kulit sebelum menggunakan popok.', 'Wait until the cream is absorbed into the skin before putting on a diaper.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (413, 71, 'Biarkan sebentar hingga krim meresap pada kulit sebelum menggunakan popok.', 'Wait until the cream is absorbed into the skin before putting on a diaper.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (414, 71, 'Dapat digunakan setiap hari atau setiap diperlukan.', 'For daily use or as needed.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (415, 71, 'Dapat digunakan setiap hari atau setiap diperlukan.', 'For daily use or as needed.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (416, 72, 'Busakan sabun Belsoap Original dengan air.', 'Foam Belsoap Original with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (417, 72, 'Busakan sabun Belsoap Original dengan air.', 'Foam Belsoap Original with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (418, 72, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (419, 72, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (420, 72, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (421, 72, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (422, 73, 'Busakan sabun Belsoap Soft Floral dengan air.', 'Foam BelsoapSoft Floral with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (423, 73, 'Busakan sabun Belsoap Soft Floral dengan air.', 'Foam BelsoapSoft Floral with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (424, 73, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (425, 73, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (426, 73, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (427, 73, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (428, 74, 'Busakan sabun Belsoap White Musk dengan air.', 'Foam Belsoap White Musk with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (429, 74, 'Busakan sabun Belsoap White Musk dengan air.', 'Foam Belsoap White Musk with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (430, 74, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (431, 74, 'Usapkan secara lembut pada seluruh tubuh yang telah dibasahi dengan air.', 'Gently apply to the entire body that has been moistened with water.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (432, 74, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (433, 74, 'Bilas hingga tidak ada busa dan sisa sabun.', 'Rinse thoroughly.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (434, 75, 'Gunakan Blacksoap black cleansing bar sebagai pengganti sabun kesehatan untuk mandi.', 'Use Blacksoap black cleansing bar as a substitute for health soap for bathing.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (435, 75, 'Gunakan Blacksoap black cleansing bar sebagai pengganti sabun kesehatan untuk mandi.', 'Use Blacksoap black cleansing bar as a substitute for health soap for bathing.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (436, 75, 'Dapat digunakan setiap hari.', 'For daily use.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (437, 75, 'Dapat digunakan setiap hari.', 'For daily use.', NULL, NULL, 'live');
INSERT INTO `product_htu` VALUES (438, 76, 'Dewasa: 1 kaplet sehari atau sesuai anjuran dokter.', 'Adults: 1 caplet per day or as doctor\'s prescription.', NULL, NULL, 'preview');
INSERT INTO `product_htu` VALUES (439, 76, 'Dewasa: 1 kaplet sehari atau sesuai anjuran dokter.', 'Adults: 1 caplet per day or as doctor\'s prescription.', NULL, NULL, 'live');

SET FOREIGN_KEY_CHECKS = 1;
